
FROM python:3.10slim


WORKDIR /app


COPY frontend/requirements.txt ./requirements.txt


RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY frontend  ./frontend

EXPOSE 8501

CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
